# Generated by Django 2.2.1 on 2019-05-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deadline', models.CharField(max_length=100, verbose_name='DeadLine')),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now=True, verbose_name='Дата получения заказа')),
                ('number_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('earned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена клиента')),
                ('status', models.IntegerField(choices=[(0, 'Not completed'), (1, 'Completed')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Earning',
                'verbose_name_plural': 'Earnings',
            },
        ),
        migrations.CreateModel(
            name='FormatOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Format of order')),
            ],
            options={
                'verbose_name': 'Format of order',
                'verbose_name_plural': 'Format of orders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of order')),
                ('type_order', models.CharField(max_length=100, verbose_name='Type of order')),
                ('deadline_writer', models.DateTimeField(verbose_name='Deadline by writer')),
                ('feedback', models.TextField(verbose_name='Feedback')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprofile.Client', verbose_name='Client')),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apporders.DeadLine', verbose_name='Deadline')),
                ('format_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apporders.FormatOrder', verbose_name='Format of order')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appprofile.Manager', verbose_name='Responsible manager')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appprofile.Writer', verbose_name='Responsible writer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
