# Generated by Django 2.2.1 on 2019-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения заказа'),
        ),
    ]
