# Generated by Django 2.2.1 on 2019-05-04 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created datetime'),
            preserve_default=False,
        ),
    ]
