# Generated by Django 2.2.1 on 2019-05-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0002_order_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'In review'), (1, 'In progress'), (2, 'Completed')], default=0, verbose_name='Status order'),
        ),
    ]
