# Generated by Django 2.2.1 on 2019-05-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
