# Generated by Django 2.2.1 on 2019-05-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/photo/managers/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/photo/writers/', verbose_name='Фото'),
        ),
    ]
