# Generated by Django 2.2.1 on 2019-05-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=200, verbose_name='Name work')),
                ('price_client', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена клиента')),
                ('price_writer', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена писателя')),
            ],
            options={
                'verbose_name': 'Type work',
                'verbose_name_plural': 'Types work',
            },
        ),
    ]
